services:
  avito-merch-app:
    container_name: avito-merch
    image: avito
    build: .
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      secret_token: ${secret_token}
    ports:
      - "8080:8080"
    depends_on:
      avito-merch-db:
        condition: service_healthy
  avito-merch-db:
    container_name: avito-merch-db
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  pgdata: